---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  selector:
    matchLabels:
      app: reddits
  replicas: 1
  template:
    metadata:
      labels:
        app: reddits
    spec:
      containers:
      - name: worker
        image: kaluzny1995/worker:latest
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq-svc:5672"
          - name: CELERY_RESULT_BACKEND
            value: "rpc"
          - name: CELERYBEAT_MINUTES_INTERVAL
            value: "2"
          - name: INFLUXDB_HOST
            value: "influxdb-svc"
          - name: INFLUXDB_PORT
            value: "8086"
          - name: MONGODB_HOST
            value: "mongodb-svc"
          - name: MONGODB_PORT
            value: "27017"
        command: ['celery', 'worker', '--app=worker.app', '--beat']
