---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: reddits
spec:
  selector:
    app: reddits
    role: mongo
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
