---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: reddits
spec:
  selector:
    app: reddits
  clusterIP: None
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
