---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.grafana.persistentVolumeClaim.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
