---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.grafana.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/grafana"
