---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.influxDB.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.influxDB.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.influxDB.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx_data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.influxDB.persistentVolumeClaim.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.influxDB.statefulset.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "{{ .Values.influxDB.service.name }}"
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.influxDB.persistentVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.influxDB.persistentVolumeClaim.name }}
      containers:
        - name: {{ .Values.influxDB.statefulset.container.name }}
          image: {{ .Values.influxDB.statefulset.container.image }}
          ports:
            - name: http
              containerPort: {{ .Values.influxDB.statefulset.container.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.influxDB.persistentVolume.name }}
              mountPath: /var/lib/influxdb
