---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoDB.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongoDB.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.mongoDB.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo_data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mongoDB.persistentVolumeClaim.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongoDB.statefulset.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "{{ .Values.mongoDB.service.name }}"
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: {{ .Values.mongoDB.persistentVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongoDB.persistentVolumeClaim.name }}
      containers:
        - name: {{ .Values.mongoDB.statefulset.container.name }}
          image: {{ .Values.mongoDB.statefulset.container.image }}
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - name: http
              containerPort: {{ .Values.mongoDB.statefulset.container.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.mongoDB.persistentVolume.name }}
              mountPath: /data/db
