---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMap.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
