---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      name: {{ .Values.postgres.service.portName }}
  clusterIP: None
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
