---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.postgres.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres_data"
