---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMap.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
data:
  POSTGRES_USER: "{{ .Values.postgres.configMap.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.configMap.password }}"
  POSTGRES_DB: "{{ .Values.postgres.configMap.dbName }}"
  PGDATA: "{{ .Values.postgres.configMap.dataPath }}"
