---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitMQ.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  type: {{ .Values.common.service.ClusterIPType }}
  ports:
  - port: {{ .Values.rabbitMQ.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitMQ.statefulset.name }}
  labels: {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitMQ.statefulset.replicaCount }}
  serviceName: "{{ .Values.rabbitMQ.service.name }}"
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      containers:
       - name: {{ .Values.rabbitMQ.statefulset.container.name }}
         image: {{ .Values.rabbitMQ.statefulset.container.image }}
         ports:
          - name: http
            containerPort: {{ .Values.rabbitMQ.statefulset.container.port }}
            protocol: TCP
         livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
