---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitMQ.statefulset.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitMQ.statefulset.replicaCount }}
  serviceName: "{{ .Values.rabbitMQ.service.name }}"
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.rabbitMQ.statefulset.container.name }}
          image: {{ .Values.rabbitMQ.statefulset.container.image }}
          ports:
            - name: {{ .Values.rabbitMQ.service.portName }}
              containerPort: {{ .Values.rabbitMQ.service.port }}
