---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redash.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.redash.service.port }}
      targetPort: {{ .Values.redash.service.port }}
      name: http
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
