---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redash.deployment.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redash.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.redash.deployment.container.redash.name }}
          image: {{ .Values.redash.deployment.container.redash.image }}
          args: ['server']
          ports:
            - name: {{ .Values.redash.service.portName }}
              containerPort: {{ .Values.redash.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.redash.configMap.name }}

        - name: {{ .Values.redash.deployment.container.redash.name }}-worker
          image: {{ .Values.redash.deployment.container.redash.image }}
          args: ['worker']
          envFrom:
            - configMapRef:
                name: {{ .Values.redash.configMap.name }}

        - name: {{ .Values.redash.deployment.container.redis.name }}
          image: {{ .Values.redash.deployment.container.redis.image }}
          command: ['redis-server', '--port', '{{ .Values.redis.service.port }}']
          ports:
            - name: {{ .Values.redis.service.portName }}
              containerPort: {{ .Values.redis.service.port }}
