---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      name: redis
  selector:
    {{- include "reddits.selectorLabels" . | nindent 4 }}
