---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.deployment.name }}
  labels:
    {{- include "reddits.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "reddits.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reddits.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.worker.deployment.container.name }}
        image: {{ .Values.worker.deployment.container.image }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ .Values.worker.configMap.name }}
        command: ['celery', 'worker', '--app=worker.app', '--beat']
        livenessProbe:
          exec:
            command:
              - echo
              - "Liveness check OK."
          initialDelaySeconds: {{ .Values.worker.deployment.container.liveDelay }}
          periodSeconds: {{ .Values.worker.deployment.container.livePeriod }}

        readinessProbe:
          exec:
            command:
              - echo
              - "Readiness check OK."
          initialDelaySeconds: {{ .Values.worker.deployment.container.readiDelay }}
          periodSeconds: {{ .Values.worker.deployment.container.readiPeriod }}
