version: '3.4'

services:

  spark-master:
    container_name: spark-master
    image: webspark
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spark_mdb
    command: /usr/spark-2.3.1/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./services/spark/data:/usr/src/app/server/main/spark_models

  spark-worker:
    image: webspark
    container_name: spark-worker
    networks:
      - spark_mdb
    command: /usr/spark-2.3.1/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./services/spark/data:/usr/src/app/server/main/spark_models
    links:
      - spark-master
    depends_on:
      - spark-master

  web:
    container_name: web
    image: webspark
    networks:
      - spark_mdb
    volumes:
      - ./services/spark/data:/usr/src/app/server/main/spark_models
    ports:
      - 5009:5000
    command: python /usr/src/app/manage.py runserver -h 0.0.0.0
    environment:
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: 27017
    links:
      - spark-master
      - spark-worker
    depends_on:
      - redis
      - spark-master
      - spark-worker

  worker:
    image: webspark
    container_name: redis-flask-worker
    networks:
      - spark_mdb
    command: spark-submit --master spark://spark-master:7077 --packages org.mongodb.spark:mongo-spark-connector_2.11:2.2.0 --class endpoint /usr/src/app/manage.py run_worker
    environment:
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: 27017
    external_links:
      - mongodb
    volumes:
      - ./services/spark/data:/usr/src/app/server/main/spark_models
    depends_on:
      - redis
      - web

  redis:
    image: redis:3.2.11
    container_name: redis-server
    networks:
      - spark_mdb

networks:
  spark_mdb:
    external: true
