---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  selector:
    matchLabels:
      app: reddits
  replicas: 1
  template:
    metadata:
      labels:
        app: reddits
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8
        ports:
          - containerPort: 5672
