---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: reddits
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: rabbitmq
  selector:
    app: reddits
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-sts
spec:
  serviceName: "rabbitmq-svc"
  selector:
    matchLabels:
      app: reddits
  replicas: 1
  template:
    metadata:
      labels:
        app: reddits
    spec:
      containers:
       - name: rabbitmq
         image: rabbitmq:3.8
         ports:
          - containerPort: 5672
