---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: reddits
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: rabbitmq
  selector:
    app: reddits
