---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: reddits
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app: reddits
