---
apiVersion: v1
kind: Service
metadata:
  name: reddits-service
  labels:
    app: reddits
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: rabbitmq

  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongodb

  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: reddits
