---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-sts
spec:
  serviceName: "influxdb-svc"
  selector:
    matchLabels:
      app: reddits
  replicas: 1
  template:
    metadata:
      labels:
        app: reddits
    spec:
      volumes:
       - name: influxdb-pv
         persistentVolumeClaim:
           claimName: influxdb-pvc
      containers:
       - name: influxdb
         image: influxdb:1.8
         ports:
          - containerPort: 8086
         volumeMounts:
          - name: influxdb-pv
            mountPath: /var/lib/influxdb
