---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sts
spec:
  serviceName: "mongodb-svc"
  selector:
    matchLabels:
      app: reddits
  replicas: 1
  template:
    metadata:
      labels:
        app: reddits
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
       - name: mongodb-pv
         persistentVolumeClaim:
           claimName: mongodb-pvc
      containers:
       - name: mongodb
         image: mongo:4.4
         command:
          - mongod
          - "--bind_ip"
          - 0.0.0.0
         ports:
          - containerPort: 27017
         volumeMounts:
          - name: mongodb-pv
            mountPath: /data/db
